import Footer from "./Footer";
import NavBar from "./NavBar";
import Head from "next/head";

const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Will Miles</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            {children}
            <Footer />
        </div>
    );
}

export default Layout;