import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Will Miles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home</h1>

    </div>
  )
}

export default Home
